language: java

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        
before_install:
 - chmod +x gradlew      
 
install:
    - pip install --user coverage

jdk:
    - oraclejdk8
    
script:
    - wget http://senorpez.servebeer.com/pcars/races/testdata.tar.gz
    - mkdir src/test/resources/assets
    - tar -zxf testdata.tar.gz -C src/test/resources/assets/
    - ./gradlew assemble
    - ./gradlew check
    
after_script:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)